### ISSUE TITLE
Moonwall does not automatically create "node_logs" folder

### ISSUE THREAD

**Issue by tmpolaczyk** [Moonsong-Labs/moonwall#295]
It was reported in the Tanssi repo:

https://github.com/moondance-labs/tanssi/issues/303

```
node:fs:1452
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/user/development/tanssi/test/tmp/node_logs'
    at Object.readdirSync (node:fs:1452:3)
    at reportLogLocation (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/chunk-LXB5S76P.js:18:21)
    at runNetworkCmd (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/chunk-KOVVJTEW.js:127:3)
    at async Object.handler (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/cmds/entrypoint.js:123:5) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/user/development/tanssi/test/tmp/node_logs'
}

Node.js v18.16.0
```

**Comment by timbrinded** [comment]
Fixed in 4.3.0
