### ISSUE TITLE
Error importing config on fresh install

### ISSUE THREAD

**Issue by timbrinded** [Moonsong-Labs/moonwall#366]
You should be able to run moonwall even without a config. However without one it'll error:

```sh
pnpm --package=@moonwall/cli@latest dlx moonwall

? Main Menu - Please select one of the following: 2) Artifact Downloader:                Fetch artifacts (x86) from GitHub repos
[Error: ENOENT: no such file or directory, open '/home/timbo/workspaces/subxttest/moonwall.config.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/home/timbo/workspaces/subxttest/moonwall.config.json'
}
file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-3IRCD3RX.js:100
throw new Error(`Error import config at ${filePath}`);
^

Error: Error import config at /home/timbo/workspaces/subxttest/moonwall.config.json
at importAsyncConfig (file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-3IRCD3RX.js:100:11)
at async allReposAsync (file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-UNICVURW.js:24:24)
at async resolveDownloadChoice (file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-UEU6ZICD.js:357:20)
at async mainMenu (file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-UEU6ZICD.js:261:7)
at async main (file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/chunk-UEU6ZICD.js:173:9)
at async file:///home/timbo/.local/share/pnpm/store/v3/tmp/dlx-251986/node_modules/.pnpm/@moonwall+cli@4.7.5_@acala-network+chopsticks@0.9.7_@polkadot+api@10.11.2_@types+node@20.11.6_yku4xauvent4wiloxd547yvyfu/node_modules/@moonwall/cli/dist/cmds/entrypoint.js:132:3

Node.js v20.11.0
```

**Comment by timbrinded** [comment]
No longer seen in latest
