### ISSUE TITLE
Error message when missing binary is hard to read

### ISSUE THREAD

**Issue by crystalin** [Moonsong-Labs/moonwall#41]
I tried to add zombienet and got:

```
? Main Menu - Please select one of the following: 2) Network Launcher & Toolbox:         Launch network, access tools: tail logs, interactive tests etc.
? Select a environment to run Env: zombie_test     (zombie)
🧟 Spawning zombie nodes ...
Error:           Error: Command failed with exit code 127: bash -c tmp/polkadot build-spec --chain rococo-local --disable-default-bootnode > /tmp/zombie-51d516610813647164741c1269b6a9ad_-11076-t0sEablUBVug/cfg/rococo-local-plain.json
bash: line 1: tmp/polkadot: No such file or directory

undefined
/home/crystalin/projects/moonbeam/test/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 2: bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
    at makeError (/home/crystalin/projects/moonbeam/test/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/crystalin/projects/moonbeam/test/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 2: bash -c kill -9 ',
  command: 'bash -c kill -9 ',
  escapedCommand: 'bash -c "kill -9 "',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.15.0
```

**Comment by timbrinded** [comment]
fixed in https://github.com/Moonsong-Labs/moonwall/pull/53
